RG_CeladonCity_MapScripts::
	.byte 0

RG_CeladonCity_EventScript_TrainerTips1::
	msgbox RG_CeladonCity_Text_ExplainXAccuracyDireHit, MSGBOX_SIGN
	end

RG_CeladonCity_EventScript_CitySign::
	msgbox RG_CeladonCity_Text_CitySign, MSGBOX_SIGN
	end

RG_CeladonCity_EventScript_GymSign::
	msgbox RG_CeladonCity_Text_GymSign, MSGBOX_SIGN
	end

RG_CeladonCity_EventScript_MansionSign::
	msgbox RG_CeladonCity_Text_MansionSign, MSGBOX_SIGN
	end

RG_CeladonCity_EventScript_DeptStoreSign::
	msgbox RG_CeladonCity_Text_DeptStoreSign, MSGBOX_SIGN
	end

RG_CeladonCity_EventScript_TrainerTips2::
	msgbox RG_CeladonCity_Text_GuardSpecProtectsFromStatus, MSGBOX_SIGN
	end

RG_CeladonCity_EventScript_PrizeExchangeSign::
	msgbox RG_CeladonCity_Text_PrizeExchangeSign, MSGBOX_SIGN
	end

RG_CeladonCity_EventScript_GameCornerSign::
	msgbox RG_CeladonCity_Text_GameCornerSign, MSGBOX_SIGN
	end

RG_CeladonCity_Text_ExplainXAccuracyDireHit::
    .string "TRAINER TIPS\p"
    .string "X ACCURACY boosts the accuracy of\n"
    .string "techniques.\p"
    .string "DIRE HIT jacks up the likelihood\n"
    .string "of critical hits.\p"
    .string "Get your items at the CELADON\n"
    .string "DEPT. STORE!$"

RG_CeladonCity_Text_CitySign::
    .string "CELADON CITY\n"
    .string "The City of Rainbow Dreams$"

RG_CeladonCity_Text_GymSign::
    .string "CELADON CITY POKéMON GYM\n"
    .string "LEADER: ERIKA\l"
    .string "The Nature-Loving Princess!$"

RG_CeladonCity_Text_MansionSign::
    .string "CELADON MANSION$"

RG_CeladonCity_Text_DeptStoreSign::
    .string "Find what you need at the\n"
    .string "CELADON DEPT. STORE!$"

RG_CeladonCity_Text_GuardSpecProtectsFromStatus::
    .string "TRAINER TIPS\p"
    .string "GUARD SPEC. protects POKéMON\n"
    .string "from status-reduction moves during\l"
    .string "battle.\p"
    .string "Get your items at the\n"
    .string "CELADON DEPT. STORE!$"

RG_CeladonCity_Text_PrizeExchangeSign::
    .string "COINS exchanged for prizes!\n"
    .string "PRIZE EXCHANGE$"

RG_CeladonCity_Text_GameCornerSign::
    .string "ROCKET GAME CORNER\n"
    .string "The playground for grown-ups!$"
