#ifndef GUARD_CONSTANTS_DAY_NIGHT_H
#define GUARD_CONSTANTS_DAY_NIGHT_H

#define MORNING_HOUR_BEGIN 4
#define MORNING_HOUR_END   10

#define DAY_HOUR_BEGIN     10
#define DAY_HOUR_END       20

#define NIGHT_HOUR_BEGIN   20
#define NIGHT_HOUR_END     4

#define TIME_DAY 0
#define TIME_MORNING 1
#define TIME_NIGHT 2
#define TIMES_OF_DAY_COUNT 3

#endif  // GUARD_CONSTANTS_DAY_NIGHT_H
