#ifndef GUARD_FIELD_EFFECT_CONSTANTS_H
#define GUARD_FIELD_EFFECT_CONSTANTS_H

#define FLDEFF_EXCLAMATION_MARK_ICON     0
#define FLDEFF_USE_CUT_ON_GRASS          1
#define FLDEFF_USE_CUT_ON_TREE           2
#define FLDEFF_SHADOW                    3
#define FLDEFF_TALL_GRASS                4
#define FLDEFF_RIPPLE                    5
#define FLDEFF_FIELD_MOVE_SHOW_MON       6
#define FLDEFF_ASH                       7
#define FLDEFF_SURF_BLOB                 8
#define FLDEFF_USE_SURF                  9
#define FLDEFF_DUST                      10
#define FLDEFF_USE_SECRET_POWER_CAVE     11
#define FLDEFF_JUMP_TALL_GRASS           12
#define FLDEFF_SAND_FOOTPRINTS           13
#define FLDEFF_JUMP_BIG_SPLASH           14
#define FLDEFF_SPLASH                    15
#define FLDEFF_JUMP_SMALL_SPLASH         16
#define FLDEFF_LONG_GRASS                17
#define FLDEFF_WATER_SURFACING           18
#define FLDEFF_BERRY_TREE_GROWTH_SPARKLE 19
#define FLDEFF_DEEP_SAND_FOOTPRINTS      20
#define FLDEFF_POKECENTER_HEAL           21
#define FLDEFF_USE_SECRET_POWER_TREE     22
#define FLDEFF_USE_SECRET_POWER_SHRUB    23
#define FLDEFF_TREE_DISGUISE             24
#define FLDEFF_MOUNTAIN_DISGUISE         25
#define FLDEFF_NPCFLY_OUT                26
#define FLDEFF_USE_FLY                   27
#define FLDEFF_FLY_IN                    28
#define FLDEFF_QUESTION_MARK_ICON        29
#define FLDEFF_FEET_IN_FLOWING_WATER     30
#define FLDEFF_BIKE_TIRE_TRACKS          31
#define FLDEFF_USE_ROCK_SMASH            32
#define FLDEFF_USE_DIG                   33
#define FLDEFF_SAND_PILE                 34
#define FLDEFF_USE_STRENGTH              35
#define FLDEFF_SHORT_GRASS               36
#define FLDEFF_HOT_SPRINGS_WATER         37
#define FLDEFF_USE_WATERFALL             38
#define FLDEFF_USE_DIVE                  39
#define FLDEFF_POKEBALL_TRAIL            40
#define FLDEFF_HEART_ICON                41
#define FLDEFF_ASH_PUFF                  42
#define FLDEFF_ASH_LAUNCH                43
#define FLDEFF_SWEET_SCENT               44
#define FLDEFF_SAND_PILLAR               45
#define FLDEFF_BUBBLES                   46
#define FLDEFF_SPARKLE                   47
#define FLDEFF_SECRET_POWER_CAVE         48
#define FLDEFF_SECRET_POWER_TREE         49
#define FLDEFF_SECRET_POWER_SHRUB        50
#define FLDEFF_CUT_GRASS                 51
#define FLDEFF_FIELD_MOVE_SHOW_MON_INIT  52
#define FLDEFF_USE_TOMB_PUZZLE_EFFECT    53
#define FLDEFF_PCTURN_ON                 54
#define FLDEFF_HALL_OF_FAME_RECORD       55
#define FLDEFF_USE_TELEPORT              56
#define FLDEFF_RAYQUAZA_SPOTLIGHT        57
#define FLDEFF_DESTROY_DEOXYS_ROCK       58
#define FLDEFF_MOVE_DEOXYS_ROCK          59

#define FLDEFFOBJ_SHADOW_S              0
#define FLDEFFOBJ_SHADOW_M              1
#define FLDEFFOBJ_SHADOW_L              2
#define FLDEFFOBJ_SHADOW_XL             3
#define FLDEFFOBJ_TALL_GRASS            4
#define FLDEFFOBJ_RIPPLE                5
#define FLDEFFOBJ_ASH                   6
#define FLDEFFOBJ_SURF_BLOB             7
#define FLDEFFOBJ_ARROW                 8
#define FLDEFFOBJ_GROUND_IMPACT_DUST    9
#define FLDEFFOBJ_JUMP_TALL_GRASS       10
#define FLDEFFOBJ_SAND_FOOTPRINTS       11
#define FLDEFFOBJ_JUMP_BIG_SPLASH       12
#define FLDEFFOBJ_SPLASH                13
#define FLDEFFOBJ_JUMP_SMALL_SPLASH     14
#define FLDEFFOBJ_LONG_GRASS            15
#define FLDEFFOBJ_WATER_SURFACING       16
#define FLDEFFOBJ_REFLECTION_DISTORTION 17
#define FLDEFFOBJ_SPARKLE               18
#define FLDEFFOBJ_DEEP_SAND_FOOTPRINTS  19
#define FLDEFFOBJ_TREE_DISGUISE         20
#define FLDEFFOBJ_MOUNTAIN_DISGUISE     21
#define FLDEFFOBJ_BIRD                  22
#define FLDEFFOBJ_BIKE_TIRE_TRACKS      23
#define FLDEFFOBJ_SAND_PILE             24
#define FLDEFFOBJ_SHORT_GRASS           25
#define FLDEFFOBJ_HOT_SPRINGS_WATER     26
#define FLDEFFOBJ_ASH_PUFF              27
#define FLDEFFOBJ_ASH_LAUNCH            28
#define FLDEFFOBJ_BUBBLES               29
#define FLDEFFOBJ_SMALL_SPARKLE         30
#define FLDEFFOBJ_RAYQUAZA              31
#define FLDEFFOBJ_LONG_GRASS_COVERED    32

#define FLDEFF_PAL_TAG_GENERAL_3          0x1000
#define FLDEFF_PAL_TAG_SECRET_POWER_TREE  0x1003
#define FLDEFF_PAL_TAG_GENERAL_0          0x1004
#define FLDEFF_PAL_TAG_GENERAL_1          0x1005
#define FLDEFF_PAL_TAG_ARROW              0x1006
#define FLDEFF_PAL_TAG_POKEBALL_GLOW      0x1007
#define FLDEFF_PAL_TAG_SECRET_POWER_PLANT 0x1008
#define FLDEFF_PAL_TAG_POKEBALL_TRAIL     0x1009
#define FLDEFF_PAL_TAG_GENERAL_2          0x100D
#define FLDEFF_PAL_TAG_SAND_PILLAR        0x100E
#define FLDEFF_PAL_TAG_HOF_MONITOR        0x100F

#endif // GUARD_FIELD_EFFECT_CONSTANTS_H
