RG_CeladonCity_Condominiums_RoofRoom_MapScripts::
	.byte 0

RG_CeladonCity_Condominiums_RoofRoom_EventScript_TMsPamphlet::
	msgbox RG_CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs, MSGBOX_SIGN
	end

RG_CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs::
    .string "It's a pamphlet on TMs.\p"
    .string "… …\p"
    .string "There are fifty TMs in all.\p"
    .string "There are also seven HMs that\n"
    .string "can be used repeatedly.\p"
    .string "SILPH CO.$"
