RG_SaffronCity_MapScripts::
	.byte 0

RG_SaffronCity_EventScript_CitySign::
	msgbox RG_SaffronCity_Text_CitySign, MSGBOX_SIGN
	end

RG_SaffronCity_EventScript_DojoSign::
	msgbox RG_SaffronCity_Text_FightingDojo, MSGBOX_SIGN
	end

RG_SaffronCity_EventScript_GymSign::
	msgbox RG_SaffronCity_Text_GymSign, MSGBOX_SIGN
	end

RG_SaffronCity_EventScript_TrainerTips1::
	msgbox RG_SaffronCity_Text_FullHealCuresStatus, MSGBOX_SIGN
	end

RG_SaffronCity_EventScript_TrainerTips2::
	msgbox RG_SaffronCity_Text_GreatBallImprovedCatchRate, MSGBOX_SIGN
	end

RG_SaffronCity_EventScript_SilphCoSign::
	msgbox RG_SaffronCity_Text_SilphCoSign, MSGBOX_SIGN
	end

RG_SaffronCity_EventScript_MrPsychicsHouseSign::
	msgbox RG_SaffronCity_Text_MrPsychicsHouse, MSGBOX_SIGN
	end

RG_SaffronCity_EventScript_SilphProductSign::
	msgbox RG_SaffronCity_Text_SilphsLatestProduct, MSGBOX_SIGN
	end

RG_SaffronCity_EventScript_TrainerFanClubSign::
	msgbox RG_SaffronCity_Text_TrainerFanClubSign, MSGBOX_SIGN
	end

RG_SaffronCity_Text_CitySign::
    .string "SAFFRON CITY\n"
    .string "Shining, Golden Land of Commerce$"

RG_SaffronCity_Text_FightingDojo::
    .string "FIGHTING DOJO$"

RG_SaffronCity_Text_GymSign::
    .string "SAFFRON CITY POKéMON GYM\n"
    .string "LEADER: SABRINA\l"
    .string "The Master of PSYCHIC POKéMON!$"

RG_SaffronCity_Text_FullHealCuresStatus::
    .string "TRAINER TIPS\p"
    .string "FULL HEAL cures all ailments like\n"
    .string "burns, paralysis, poisoning,\l"
    .string "freezing, and sleep.\p"
    .string "It costs a bit more, but it's more\n"
    .string "convenient than buying other items.$"

RG_SaffronCity_Text_GreatBallImprovedCatchRate::
    .string "TRAINER TIPS\p"
    .string "The new GREAT BALL offers improved\n"
    .string "catching rates.\p"
    .string "Try it on those hard-to-catch\n"
    .string "POKéMON.$"

RG_SaffronCity_Text_SilphCoSign::
    .string "SILPH CO. OFFICE BUILDING$"

RG_SaffronCity_Text_MrPsychicsHouse::
    .string "MR. PSYCHIC'S HOUSE$"

RG_SaffronCity_Text_SilphsLatestProduct::
    .string "SILPH's latest product!\n"
    .string "Release to be determined…$"

RG_SaffronCity_Text_TrainerFanClubSign::
    .string "POKéMON TRAINER FAN CLUB\p"
    .string "Many TRAINERS have scribbled their\n"
    .string "names on this sign.$"
